### ISSUE TITLE
write better readme

### ISSUE THREAD

**Issue by vcap-kali** [ztrhgf/LAPS#2]
First of all, naming a directory to be `AdmPwd.PS` with `.ps` is beyond confusing, why?

In the readme, "import modules AdmPwd.PS", okay how? You want people to be able to follow along and use the fruit of your labor yes? Without having to do a full code review just to learn how to import it

**Comment by ztrhgf** [comment]
Modules are placed in the root of this repository so I thought it is quite obvious what to do :)
Anyway, I've updated the readme.

PS: AdmPwd.PS is the official name of the (not mine) module
